return {
    descriptions = {
        Joker = {
            j_leper_Leprechaun = {
                name = 'Leprechaun',
                text = {
                    'Every time a {C:attention}lucky{} card',
                    '{C:green} successfully{} triggers {C:attention} BOTH{}',
                    'the {C:red} mult{} {C:attention} AND{} the {C:money} money{}',
                    'increase both the lucky cards listed {C:green} probabilities{} by 1',
                }
            },
            j_leper_Hotstreak = {
                name = 'Hotstreak',
                text = {
                    '{C:green} #1# in #2#{} chance to retrigger played lucky card',
                    '{C:green} #3# in #4#{} chance to retrigger played lucky card a second time',
                    '{C:green} #5# in #6#{} chance to retrigger played lucky card a third time',
                    '{C:green} #7# in #8#{} chance to retrigger played lucky card a fourth time',
                    '{C:green} #9# in #10#{} chance to retrigger played lucky card a fifth time',
                    '{C:green} #11# in #12#{} chance to retrigger played lucky card a sixth time',
                    '{C:green} #13# in #14#{] chance to retrigger played lucky card a seventh time',
                }
            },
            j_leper_Overwhelming_Love = {
                name = 'Overwhelming Love',
                text = {
                    'Retrigger all',
                    'played {C:hearts}Heart{} cards',
                }
            },
            j_leper_Overpowering_Might = {
                name = 'Overpowering Might',
                text = {
                    'Retrigger all',
                    'played {C:clubs}Club{} cards',
                }
            },
            j_leper_Overunning_Tactics = {
                name = 'Overunning Tactics',
                text = {
                    'Retrigger all',
                    'played {C:spades}Spade{} cards',
                }
            },
            j_leper_Overflowing_Wealth = {
                name = 'Overflowing Wealth',
                text = {
                    'Retrigger all',
                    'played {C:diamonds}Diamond{} cards',
                }
            },
            j_leper_Vampire_Queen = {
                name = 'Vampire Queen',
                text = {
                    'All cards give {X:mult,C:white}X#2#{} Mult on score,',
                    'this number increases by {X:mult,C:white}X#1#{} every time a {C:attention}Sealed card{} is played',
                    'removes card {C:attention}Seal',
                }
            },
            j_leper_Sealed_Arcanist = {
                name = 'Sealed Arcanist',
                text = {
                    '{C:attention}+#3#{} Consumable Slots',
                    '{C:tarot} Purple{} seals have a {C:green}#1# in #2#{} chance to give a',
                    '{C:spectral} spectral{} card instead when discarded',
                }
            },
            j_leper_Sealed_Explorer = {
                name = 'Sealed Explorer',
                text = {
                    'retrigger all {C:planet}Blue{} seals',
                    'planet cards generated by {C:planet}Blue{} seals that go over the consumable limit',
                    'have a {C:green}#1# in #2#{} chance to become {C:negative}negative{}',
                }
            },
            j_leper_Sealed_Conqueror = {
                name = 'Sealed Conqueror',
                text = {
                    'retrigger all {C:mult}Red{} seals an additional time',
                    '{C:green} #1# in #2#{} chance to retrigger {C:mult}Red{} seals a third time',
                }
            },
            j_leper_Sealed_Merchant = {
                name = 'Sealed Merchant',
                text = {
                    '{C:attention} Gold{} seals give {C:money}6${} when scored',
                    '{C:green} #1# in #2#{} chance for {C:Attention}Gold{} seals to give {C:money}30${}',
                }
            },
            j_leper_Jillpot = {
                name = 'Jillpot',
                text = {
                    'if hand is a {C:attention}Three of a Kind{}',
                    'that contains only {C:attention}7s{}',
                    'each played card has a {C:green}#1# in #2#{} chance',
                    'to be retriggered {C:attention}7{} times',
                },
            },
            j_leper_Jackpot = {
                name = 'Jackpot',
                text = {
                    'if hand is a {C:attention} Three of a Kind{}',
                    'that contains only {C:attention}7s{}',
                    'each played card has a {C:green} #1# in #2#{} chance',
                    'to give {X:mult,C:white} X#3# {} Mult when scored',

                }
            },
            j_leper_Loaded_Dice = {
                name = 'Loaded Dice',
                text = {
                    'Increase all {C:attention}listed',
                    '{C:green,E:1,S:1.1}probabilities tenfold',
                    '{C:inactive}(ex: {C:green}1 in 3{C:inactive} -> {C:green}10 in 3{C:inactive})',
                    '{C:green} #2# in #3#{} chance this',
                    'card is confiscated',
                    'at end of round',
                }
            }
        }
    }
}
