return {
    descriptions = {
        Joker = {
            j_leper_Leprechaun         = {
                name = 'Leprechaun',
                text = {
                    'Whenever a scored {C:attention}Lucky{} card grants both',
                    '{C:mult}Mult{} and {C:money}Money{}',
                    'permanently increase that cards {C:attention}listed{} {C:green}probabilities{} by 1',
                }
            },
            j_leper_Hotstreak          = {
                name = 'Hotstreak',
                text = {
                    '{C:attention}played Lucky{} cards are retriggered up to 7 times',
                    'the first retrigger has a {C:green} #1# in #2#{} chance',
                    'Every additional retrigger halves the chance of the next',
                }
            },
            j_leper_Overwhelming_Love  = {
                name = 'Overwhelming Love',
                text = {
                    'Retrigger all',
                    'played {C:hearts}Heart{} cards',
                }
            },
            j_leper_Overpowering_Might = {
                name = 'Overpowering Might',
                text = {
                    'Retrigger all',
                    'played {C:clubs}Club{} cards',
                }
            },
            j_leper_Overunning_Tactics = {
                name = 'Overunning Tactics',
                text = {
                    'Retrigger all',
                    'played {C:spades}Spade{} cards',
                }
            },
            j_leper_Overflowing_Wealth = {
                name = 'Overflowing Wealth',
                text = {
                    'Retrigger all',
                    'played {C:diamonds}Diamond{} cards',
                }
            },
            j_leper_Vampire_Queen      = {
                name = 'Vampire Queen',
                text = {
                    'All cards give {X:mult,C:white}X#2#{} Mult on score,',
                    'this number increases by {X:mult,C:white}X#1#{} every time a {C:attention}Sealed card{} is played',
                    'removes card {C:attention}Seal',
                }
            },
            j_leper_Sealed_Arcanist    = {
                name = 'Sealed Arcanist',
                text = {
                    '{C:attention}+#3#{} Consumable Slots',
                    '{C:tarot} Purple{} seals have a {C:green}#1# in #2#{} chance to give a',
                    '{C:spectral} spectral{} card instead when discarded',
                }
            },
            j_leper_Sealed_Explorer
                                       = {
                name = 'Sealed Explorer',
                text = {
                    'retrigger all {C:attention} held in hand',
                    'abilities on cards with a {C:planet}Blue{} seal',
                    'exess {C:planet}planet{} cards generated by {C:planet}Blue{} seals',
                    'have a {C:green}#1# in #2#{} chance to become {C:negative}negative{}',
                }
            },
            j_leper_Sealed_Conqueror   = {
                name = 'Sealed Conqueror',
                text = {
                    'retrigger all {C:mult}Red{} seals an additional time',
                    '{C:green} #1# in #2#{} chance to retrigger {C:mult}Red{} seals a third time',
                }
            },
            j_leper_Sealed_Merchant    = {
                name = 'Sealed Merchant',
                text = {
                    '{C:attention} Gold{} seals give {C:money}6${} when scored',
                    '{C:green} #1# in #2#{} chance for {C:Attention}Gold{} seals to give {C:money}30${}',
                }
            },
            j_leper_Jillpot            = {
                name = 'Jillpot',
                text = {
                    'if hand is a {C:attention}Three of a Kind{}',
                    'that contains only {C:attention}7s{}',
                    'each played card has a {C:green}#1# in #2#{} chance',
                    'to be retriggered {C:attention}7{} times',
                },
            },
            j_leper_Jackpot            = {
                name = 'Jackpot',
                text = {
                    'if hand is a {C:attention} Three of a Kind{}',
                    'that contains only {C:attention}7s{}',
                    'each played card has a {C:green} #1# in #2#{} chance',
                    'to give {X:mult,C:white} X#3# {} Mult when scored',

                }
            },
            j_leper_Loaded_Dice        = {
                name = 'Loaded Dice',
                text = {
                    'Increase all {C:attention}listed',
                    '{C:green,E:1,S:1.1}probabilities tenfold',
                    '{C:inactive}(ex: {C:green}1 in 3{C:inactive} -> {C:green}10 in 3{C:inactive})',
                    '{C:green} #2# in #3#{} chance this',
                    'card is confiscated',
                    'at end of round',
                }
            }
        }
    }
}
